[package]
name = "mgcoord"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mgrepl = { path = "../mgrepl" }
openraft = { workspace = true }
tokio = { workspace = true }
mgcore = { path = "../mgcore" }
mgrpc = { path = "../mgrpc" }
mgstorage = { path = "../mgstorage" }
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
bincode = "1"

[dev-dependencies]
bincode = "1"
tempfile = "3"
