[package]
name = "mgglue"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mgcore.workspace = true
mgstorage.workspace = true
mginterp.workspace = true
mgparser.workspace = true
mgcatalog.workspace = true
mgauth.workspace = true
mgdbms.workspace = true
mgaudit.workspace = true
tracing.workspace = true
tokio.workspace = true
