[package]
name = "mgstorage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mgcore = { path = "../mgcore" }
mgslk = { path = "../mgslk" }
mgdisk = { path = "../mgdisk" }
mgvector = { path = "../mgvector" }
rocksdb = { workspace = true }
crossbeam-epoch = "0.9"
crossbeam-skiplist = { workspace = true }
tantivy = { workspace = true }
lru = "0.12"
num_cpus = "1.16"
