[package]
name = "mginterp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mgcore = { path = "../mgcore" }
mgparser = { path = "../mgparser" }
mgstorage = { path = "../mgstorage" }
mgcatalog = { path = "../mgcatalog" }
mgquery = { path = "../mgquery" }
mgplanner = { path = "../mgplanner" }
mgauth = { path = "../mgauth" }
mgdbms = { path = "../mgdbms" }
mgvector = { path = "../mgvector" }
mgflags = { path = "../mgflags" }
csv = "1.3"
chrono = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
regex = "1"
ureq = "3"
lru = "0.12"
